# Generated by Django 4.2.3 on 2023-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_course_student_graduation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='studying_year',
            field=models.CharField(max_length=100),
        ),
    ]
