# Generated by Django 4.2.3 on 2023-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_course_alter_student_graduation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
